config: !OpnManage
  server: !Interface
    name: wg0
    address: 100.64.10.1/32
    listen_address: opnmanage.i-solutions.net.au
    listen_port: 51820
    private_key: CMD47jW11nDUkbyoEz8HnlL2q0KWyoXNwC2WF2PYTVM=
  techs:
    - !Tech
      name: Nathan
      private_key: CPHB7zd4x9cR/o36n2WqtowRMzTEBtJS/ptqjl1ydEE=
      address: 100.64.10.2/32
      allowed_ips: 100.64.101.0/24,100.64.102.0/24
    - !Tech
      name: Roberto
      private_key: CAxnSGairyXIUbRuQQ41h/q3RfTP07L6c5y1dHaPFGY=
      address: 100.64.10.3/32
      allowed_ips: 100.64.101.0/24,100.64.102.0/24
    - !Tech
      name: Maranda
      private_key: 8LJx5hDHTG96GiMqiPO2wTvXuG4WyAQiFiGLpjnReUY=
      address: 100.64.10.4/32
      allowed_ips: 100.64.101.0/24,100.64.102.0/24
    - !Tech
      name: John
      private_key: qOryNoq+chAdZaQ6iHOqs5QIYpvLRFQIJqx8f8OKQ2s=
      address: 100.64.10.5/32
      allowed_ips: 100.64.101.0/24,100.64.102.0/24
  devices:
    - !Device
      name: IntegratedSolutions-SBC
      private_key: 4APAHDsYteyehxmxtdEVDmv68ZD10nkVy4XY6LTgWGs=
      address: 100.64.102.1/32
      allowed_ips: 100.64.10.0/24
  firewalls:
    - !Firewall
      name: IntegratedSolutions
      private_key: EI1KPTPUAhBPMY/iYOd4chNvaW1UgWZAwqNrrJuOc3k=
      address: 100.64.101.1/32
      allowed_ips: 100.64.10.0/24
      url: https://100.64.101.1:4444/
    - !Firewall
      name: Brothers
      private_key: iJmnDXPACqadd0z63tnKCh6LLO03vNNmsUxmi9wJ82M=
      address: 100.64.101.2/32
      allowed_ips: 100.64.10.0/24
      url: https://100.64.101.2:4444/
    - !Firewall
      name: FullerSports
      private_key: qIpSCnDFrIiYcJEoDsZpxDXmCSEfg3OGRJiguozFtXE=
      address: 100.64.101.3/32
      allowed_ips: 100.64.10.0/24
      url: https://100.64.101.3:4444/
    - !Firewall
      name: gateway-cns.cardzilla.com.au
      private_key: gDAiuq8q9S/2i+0ngL6eiGupVe0Y25THPAyVEEjRMUE=
      address: 100.64.101.4/32
      allowed_ips: 100.64.10.0/24
      url: https://100.64.101.4:4444/
    - !Firewall
      name: gateway.trinityprinters.com.au
      private_key: uLI28xJmmkSkDrVOJ5QQw2+8u06tAQzFMLv3aZz353E=
      address: 100.64.101.5/32
      allowed_ips: 100.64.10.0/24
      url: https://100.64.101.5:4444/
    - !Firewall
      name: gateway-tsv.cardzilla.com.au
      private_key: uNVboqHzgWXKS1ya3D8c0Oxv8j3znv2zXK0PsCTYz3c=
      address: 100.64.101.6/32
      allowed_ips: 100.64.10.0/24
      url: https://100.64.101.6:4444/
    - !Firewall
      name: YKBC
      private_key: eJS+NLpXNg7K9T5/KJaOJNo9u9dI6NJGGRck49W2H08=
      address: 100.64.101.7/32
      allowed_ips: 100.64.10.0/24
      url: https://100.64.101.7:4444/
    - !Firewall
      name: FrankLowe
      private_key: YPOMf/Vs8xtpwHdHZ6P8kItiFWHSyEUCKiaLF1bPTVU=
      address: 100.64.101.8/32
      allowed_ips: 100.64.10.0/24
      url: https://100.64.101.8:4444/
    - !Firewall
      name: PnL Accounting
      private_key: IEPSGTq3nrlrYOHAy/nMD+pv33ugIaSZp9SeSDcld24=
      address: 100.64.101.9/32
      allowed_ips: 100.64.10.0/24
      url: https://100.64.101.9:4444/
    - !Firewall
      name: StanWilliamsPark
      private_key: OPtbTZ6KytQ/wfjotts+uv1ju4/f9rqZXVH85JUaL18=
      address: 100.64.101.10/32
      allowed_ips: 100.64.10.0/24
      url: https://100.64.101.10:4444/
    - !Firewall
      name: DRD
      private_key: mCRlpYATiZhpKKZxvLSRyRbealtVRH4FSl6Vp9jBvWM=
      address: 100.64.101.11/32
      allowed_ips: 100.64.10.0/24
      url: https://100.64.101.11:4444/
    - !Firewall
      name: BusinessAndWealth
      private_key: MCq6EnSNkCwPgAnfPESnEbDygrBiWNGhU+N8flA7Jls=
      address: 100.64.101.12/32
      allowed_ips: 100.64.10.0/24
      url: https://100.64.101.12:4444/
    - !Firewall
      name: Marino-CNS
      private_key: +HOvGdkyCikUa2OOct21z9CRudaWK0SpWOwZJ3LVNWM=
      address: 100.64.101.13/32
      allowed_ips: 100.64.10.0/24
      url: https://100.64.101.13:4444/
    - !Firewall
      name: Marino-EDM
      private_key: sDy7568k21gkD2yv7GQ+I5ZrJH9e7scRk6ZtGn5nOVw=
      address: 100.64.101.14/32
      allowed_ips: 100.64.10.0/24
      url: https://100.64.101.14:4444/
    - !Firewall
      name: Marino-IFL
      private_key: aNfCKV43skW97lPUkRJyzDiOboxv8zsjeP7ufY2eK18=
      address: 100.64.101.15/32
      allowed_ips: 100.64.10.0/24
      url: https://100.64.101.15:4444/
    - !Firewall
      name: Marino-PTD
      private_key: COGZsATb8ldB9KIPH6zrCqHOJCsJORgbNnjEHjHeS0o=
      address: 100.64.101.16/32
      allowed_ips: 100.64.10.0/24
      url: https://100.64.101.16:4444/
